create table if not exists users
(
    user_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR(255) NOT NULL,
    email     VARCHAR(512) NOT NULL UNIQUE
);

create table if not exists requests
(
    request_id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_description VARCHAR(1024)                     NOT NULL,
    requestor_id        BIGINT REFERENCES users (user_id) NOT NULL,
    create_date         TIMESTAMP WITHOUT TIME ZONE       NOT NULL
);

create table if not exists items
(
    item_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name   VARCHAR(255)                      NOT NULL,
    description VARCHAR(512)                      NOT NULL,
    available   BOOLEAN                           NOT NULL,
    owner_id    BIGINT REFERENCES users (user_id) NOT NULL,
    request_id  BIGINT REFERENCES requests (request_id)
);

create table if not exists bookings
(
    booking_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date TIMESTAMP WITHOUT TIME ZONE       NOT NULL,
    end_date   TIMESTAMP WITHOUT TIME ZONE       NOT NULL,
    item_id    BIGINT REFERENCES items (item_id) NOT NULL,
    booker_id  BIGINT REFERENCES users (user_id) NOT NULL,
    status     VARCHAR(25)                       NOT NULL
);

create table if not exists comments
(
    comment_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_text VARCHAR(1024)                     NOT NULL,
    item_id      BIGINT REFERENCES items (item_id) NOT NULL,
    author_id    BIGINT REFERENCES users (user_id) NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE       NOT NULL
);